name: Terraform Init and Plan

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/dev/**'
      - 'terraform/modules/**'
  workflow_dispatch:  # manual trigger

jobs:
  terraform:
    name: Terraform Init and Plan (dev)
    runs-on: ubuntu-latest
    environment: POC

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform init -reconfigure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
