name: Terraform Init, Plan and Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/dev/**'
      - 'terraform/modules/**'
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  terraform:
    name: Terraform Workflow (dev)
    runs-on: ubuntu-latest
    environment: POC

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init (with backend)
        run: terraform init -reconfigure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'  # only manual run
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Get EKS Cluster name from Terraform output
        if: github.event_name == 'workflow_dispatch'  # only manual run
        id: eks_name
        run: echo "::set-output name=cluster_name::$(terraform output -raw cluster_name)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Configure kubeconfig
        if: github.event_name == 'workflow_dispatch'  # only manual run
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name ${{ steps.eks_name.outputs.cluster_name }} --kubeconfig ./kubeconfig
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
